---

- name: Add non-free repository
  apt_repository: repo='deb http://http.debian.net/debian/ wheezy main contrib non-free' state=present update_cache=yes

- name: Add non-free security repository
  apt_repository: repo='deb http://security.debian.org wheezy/updates main contrib non-free' state=present update_cache=yes

- name: Install packages
  apt: name={{ item }}
  with_items: 
    - snmp
    - snmpd
    - libtime-format-perl
    - libxml-simple-perl
    - libxml-twig-perl
    - libdbi-perl
    - libnetaddr-ip-perl
    - libhtml-parser-perl
    - libnetaddr-ip-perl
    - xprobe
    - nmap
    - libmail-sendmail-perl
    - traceroute
    - libio-socket-inet6-perl
    - libhtml-tree-perl
    - libsnmp-perl
    - libio-socket-multicast-perl
    - libsnmp-perl
    - libjson-perl
    - sudo
    - unzip
    - snmp-mibs-downloader

- name: Copy wmi-client package to /tmp
  copy: src=wmi-client_0112-1_amd64.deb dest=/tmp mode=776

- name: Install wmi-client with dpkg
  command: dpkg -i /tmp/wmi-client_0112-1_amd64.deb
