---

- name: Install HAproxy prerequisites
  apt: name={{ item }}
  with_items:
    - build-essential
    - make
    - cmake
    - g++
    - libssl-dev
    - libpcre3-dev

- name: Clone HAproxy from github
  git: repo=https://github.com/haproxy/haproxy.git dest=/var/haproxy/src

- name: Building HAproxy from source
  command: chdir=/var/haproxy/src sudo make TARGET=linux2628 USE_STATIC_PCRE=1 USE_OPENSSL=1 clean all

- name: Installing HAproxy
  command: chdir=/var/haproxy/src make PREFIX=/usr/local/haproxy install

- name: Create /etc/haproxy/
  file: path=/etc/haproxy state=directory

- name: Copy haproxy.service
  copy: src=haproxy.service dest=/lib/systemd/system/haproxy.service

- name: Enable haproxy.service
  command: systemctl enable /lib/systemd/system/haproxy.service
